version: "3.0"
services:
  api:
    container_name: api
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - database
    networks:
      - back
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - back
networks:
  back:
    driver: bridge
    